import os
import glob
import numpy as np
import matplotlib.pyplot as plt
from stable_baselines3.common.callbacks import CheckpointCallback, BaseCallback
from stable_baselines3.common.results_plotter import load_results, ts2xy

from ai.config import RLConfig
from ai.trainer import TetrisTrainer
from ui.dashboard import UIDashboardCallback

class PruningCheckpointCallback(CheckpointCallback):
    """
    Saves checkpoints at a given interval, but automatically deletes 
    older checkpoints to ensure only the last N are kept on disk.
    """
    def __init__(self, save_freq: int, save_path: str, name_prefix: str = "dqn_tetris", keep_last_n: int = 5, **kwargs):
        super().__init__(save_freq, save_path, name_prefix, **kwargs)
        self.keep_last_n = keep_last_n

    def _on_step(self) -> bool:
        result = super()._on_step()
        
        if self.n_calls % self.save_freq == 0:
            search_pattern = os.path.join(self.save_path, f"{self.name_prefix}_*steps.zip")
            saved_files = glob.glob(search_pattern)
            saved_files.sort(key=os.path.getmtime)
            
            while len(saved_files) > self.keep_last_n:
                oldest_file = saved_files.pop(0)
                try:
                    os.remove(oldest_file)
                except OSError as e:
                    print(f"Warning: Could not delete old checkpoint {oldest_file}: {e}")
                    
        return result

class AutoReportCallback(BaseCallback):
    """
    Generates and saves a PNG graph of the training progress every X steps.
    Reads the monitor.csv file to plot raw and smoothed reward curves.
    """
    def __init__(self, log_dir: str, save_freq: int, save_path: str, verbose: int = 0):
        super().__init__(verbose)
        self.log_dir = log_dir
        self.save_freq = save_freq
        self.save_path = save_path
        os.makedirs(self.save_path, exist_ok=True)

    def _on_step(self) -> bool:
        if self.n_calls % self.save_freq == 0:
            self._generate_plot()
        return True

    def _generate_plot(self):
        try:
            # load_results reads the monitor.csv file generated by our TetrisTrainer
            x, y = ts2xy(load_results(self.log_dir), 'timesteps')
            
            if len(x) == 0:
                return

            plt.figure(figsize=(10, 5))
            
            # Plot the raw data (light and semi-transparent)
            plt.plot(x, y, color='pink', alpha=0.5, label='Episode Reward (Raw)')
            
            # Plot the moving average (smoothed, dark line) to make trends visible
            window = min(len(y), 50)
            if window > 1:
                smoothed_y = np.convolve(y, np.ones(window)/window, mode='valid')
                plt.plot(x[len(x)-len(smoothed_y):], smoothed_y, color='red', label=f'Moving Average ({window} ep)')

            # Format the graph cleanly
            plt.xlabel('Total Timesteps')
            plt.ylabel('Score / Reward')
            plt.title(f'AI Training Progress - {self.num_timesteps} Steps')
            plt.grid(True, alpha=0.3)
            plt.legend()
            
            # Save the file and explicitly close it to free up RAM
            filepath = os.path.join(self.save_path, f"training_report_{self.num_timesteps}_steps.png")
            plt.savefig(filepath, bbox_inches='tight')
            plt.close() 
            
            if self.verbose > 0:
                print(f"\n📊 Generated progress report: {filepath}")
                
        except Exception as e:
            print(f"\n⚠️ Could not generate report: {e}")

if __name__ == "__main__":
    config = RLConfig()
    
    # Target our final save file for resuming
    SAVE_PATH = "models/dqn_tetris_final"
    LOG_DIR = "./logs"
    
    trainer = TetrisTrainer(config=config, render_mode="human", load_path=SAVE_PATH, log_dir=LOG_DIR)
    
    # 1. UI Callback (Updates the Pygame dashboard)
    dashboard = UIDashboardCallback()
    
    # 2. Checkpoint Callback (Saves AI brain every 100k steps, keeps last 5)
    checkpoint_callback = PruningCheckpointCallback(
        save_freq=100_000,
        save_path="./models/checkpoints/",
        name_prefix="dqn_tetris",
        keep_last_n=5
    )
    
    # 3. Report Callback (Saves a PNG graph every 50k steps)
    report_callback = AutoReportCallback(
        log_dir=LOG_DIR,
        save_freq=50_000,
        save_path="./reports/",
        verbose=1
    )
    
    print("Starting Tetris AI Training Dashboard...")
    print("Press [SPACE] to pause. Use [UP/DOWN] arrows to adjust speed up to 1000x.")
    
    try:
        trainer.model.learn(
            total_timesteps=2_000_000,
            # We pass ALL THREE callbacks into the pipeline
            callback=[dashboard, checkpoint_callback, report_callback], 
            tb_log_name="DQN_Run",
            reset_num_timesteps=False 
        )
    except KeyboardInterrupt:
        print("\nTraining gracefully suspended by user.")
    finally:
        trainer.model.save(SAVE_PATH)
        print(f"Progress saved to {SAVE_PATH}.zip")